name:                vanityscript
version:             0.1.0.0
github:              "fumyk/vanityscript"
license:             BSD3
author:              "Vladislav Loginov"
maintainer:          "prchnq@gmail.com"
copyright:           "2022 fumyk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/vanityscript#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- parsec
- hspec

library:
  source-dirs: src

executables:
  vanityscript-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vanityscript

tests:
  vanityscript-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - vanityscript
